SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('9e3b3072-3153-414d-b2d7-1bf0789002ac', 'basic', 'multiple_choice', 'What is the purpose of a ''dye recipe'' document used in a dye house?', '["A detailed specification of exact dye types, quantities, auxiliary chemicals, temperatures, and timing needed to reproduce a specific approved shade","A document listing only the fabric''s fiber content, unrelated to dyeing instructions","A marketing document describing the final garment''s retail price","A safety data sheet unrelated to actual dyeing instructions"]'::jsonb, 'A detailed specification of exact dye types, quantities, auxiliary chemicals, temperatures, and timing needed to reproduce a specific approved shade', 'A dye recipe precisely documents everything needed to reproduce an approved shade consistently — dye types and exact quantities (%owf), auxiliary chemicals, liquor ratio, temperature profile, and timing — critical for repeatable, consistent bulk production matching an approved lab dip.', 1, '{"dye-recipe"}'::text[]),
('9e3b3072-3153-414d-b2d7-1bf0789002ac', 'intermediate', 'multiple_choice', 'Why is precise weighing/dosing of dye and chemicals (rather than approximate measurement) especially important for very pale or very deep shades?', '["Small absolute dosing errors represent a much larger PERCENTAGE error at very low or very high dye concentrations, making shade deviation more likely at these extremes","Precise dosing only matters for medium shades, never for very pale or very deep ones","Dosing precision has no relationship to the final achieved shade at any depth","Pale and deep shades are entirely insensitive to any dosing variation, unlike medium shades"]'::jsonb, 'Small absolute dosing errors represent a much larger PERCENTAGE error at very low or very high dye concentrations, making shade deviation more likely at these extremes', 'For a very pale shade requiring a tiny dye percentage, even a small absolute weighing error represents a huge relative (percentage) error in the recipe — making precise dosing especially critical at very low (or very high, concentrated) dye amounts where proportional sensitivity to error is greatest.', 2, '{"dosing-precision","pale-deep-shades"}'::text[]),
('9e3b3072-3153-414d-b2d7-1bf0789002ac', 'intermediate', 'multiple_choice', 'What is a ''dip test'' (quick shade check) sometimes used for during a dyeing process, before the cycle is fully complete?', '["Taking a small fabric/yarn sample mid-process to visually or instrumentally check progress toward the target shade before committing to the full remaining cycle","A test that only occurs after the fabric has been completely dried and packaged","A test used exclusively to check fiber content, unrelated to color","A safety test unrelated to shade or color development"]'::jsonb, 'Taking a small fabric/yarn sample mid-process to visually or instrumentally check progress toward the target shade before committing to the full remaining cycle', 'A mid-process dip test pulls a small sample to check shade progress before the full cycle finishes, allowing early correction (adding more dye, adjusting time) if the shade is trending away from target — catching problems before the full batch is affected.', 2, '{"dip-test"}'::text[]),
('9e3b3072-3153-414d-b2d7-1bf0789002ac', 'basic', 'multiple_choice', 'What is the purpose of maintaining detailed ''dye house records/logs'' (batch number, recipe used, machine, operator, results) for each production lot?', '["To enable traceability and troubleshooting — if a shade problem arises, records help identify what specifically was different about that batch","Dye house records serve no functional purpose beyond regulatory paperwork","Records are kept solely to track employee attendance, unrelated to dyeing quality","Records are only useful for accounting/invoicing, with no quality-troubleshooting value"]'::jsonb, 'To enable traceability and troubleshooting — if a shade problem arises, records help identify what specifically was different about that batch', 'Detailed batch records (recipe, machine, timing, operator, raw material lot) provide the traceability needed to investigate quality issues — if a particular batch shows a shade problem, the logged details help identify what process variable might have differed from a successful reference batch.', 1, '{"dye-house-records"}'::text[]);
COMMIT;
