module.exports = [
{ q: "A dyeing recipe calls for 2% owf (on weight of fabric) of a reactive dye. For a batch of 500 kg fabric, how many kg of dye are needed?", options: ["10 kg", "2 kg", "25 kg", "1 kg"], correct: "10 kg", exp: "Dye needed = %owf × fabric weight = 0.02 × 500 kg = 10 kg.", difficulty: "basic", tags: ["dye-recipe-calc"] },
{ q: "A dyeing recipe calls for 1.5% owf of a reactive dye. For a batch of 800 kg fabric, how many kg of dye are needed?", options: ["12 kg", "1.5 kg", "53.3 kg", "8 kg"], correct: "12 kg", exp: "Dye needed = %owf × fabric weight = 0.015 × 800 kg = 12 kg.", difficulty: "basic", tags: ["dye-recipe-calc"] },
{ q: "A dyeing machine uses a liquor ratio of 1:10 for a 300 kg fabric batch. How many liters of dye liquor are needed?", options: ["3,000 liters", "300 liters", "30 liters", "10 liters"], correct: "3,000 liters", exp: "Liquor volume = liquor ratio × fabric weight = 10 × 300 kg = 3,000 liters (assuming 1 kg fabric corresponds to 1 liter liquor unit in the ratio).", difficulty: "basic", tags: ["liquor-ratio-calc"] },
{ q: "A dyeing machine uses a liquor ratio of 1:8 for a 500 kg fabric batch. How many liters of dye liquor are needed?", options: ["4,000 liters", "500 liters", "62.5 liters", "8 liters"], correct: "4,000 liters", exp: "Liquor volume = liquor ratio × fabric weight = 8 × 500 kg = 4,000 liters.", difficulty: "basic", tags: ["liquor-ratio-calc"] },
{ q: "A recipe requires 60 g/L of salt at a liquor ratio of 1:10 for a 200 kg fabric batch. How many kg of salt are needed in total?", options: ["120 kg", "60 kg", "12 kg", "200 kg"], correct: "120 kg", exp: "Total liquor volume = 10 × 200 kg = 2,000 liters. Total salt = 60 g/L × 2,000 L = 120,000 g = 120 kg.", difficulty: "intermediate", tags: ["salt-dosing-calc"] },
{ q: "A recipe requires 40 g/L of salt at a liquor ratio of 1:12 for a 250 kg fabric batch. How many kg of salt are needed in total?", options: ["120 kg", "40 kg", "10 kg", "250 kg"], correct: "120 kg", exp: "Total liquor volume = 12 × 250 kg = 3,000 liters. Total salt = 40 g/L × 3,000 L = 120,000 g = 120 kg.", difficulty: "intermediate", tags: ["salt-dosing-calc"] },
{ q: "A dye costs $15 per kg. If a recipe uses 2% owf of this dye for a 1,000 kg fabric batch, what is the approximate total dye cost?", options: ["$300", "$15", "$30", "$1,500"], correct: "$300", exp: "Dye needed = 0.02 × 1,000 kg = 20 kg. Total cost = 20 kg × $15/kg = $300.", difficulty: "intermediate", tags: ["dye-cost-calc"] },
{ q: "A dye costs $20 per kg. If a recipe uses 1.5% owf of this dye for a 600 kg fabric batch, what is the approximate total dye cost?", options: ["$180", "$20", "$40", "$900"], correct: "$180", exp: "Dye needed = 0.015 × 600 kg = 9 kg. Total cost = 9 kg × $20/kg = $180.", difficulty: "intermediate", tags: ["dye-cost-calc"] },
{ q: "A fabric is padded and shows a wet pickup of 70% (its weight increases by 70% of its dry weight after padding). For 100 kg of dry fabric, what is the total wet weight after padding?", options: ["170 kg", "70 kg", "130 kg", "700 kg"], correct: "170 kg", exp: "Wet weight = dry weight + (wet pickup% × dry weight) = 100 + (0.70 × 100) = 100 + 70 = 170 kg.", difficulty: "intermediate", tags: ["wet-pickup-calc"] },
{ q: "A fabric is padded and shows a wet pickup of 80%. For 250 kg of dry fabric, what is the total wet weight after padding?", options: ["450 kg", "200 kg", "330 kg", "80 kg"], correct: "450 kg", exp: "Wet weight = dry weight + (wet pickup% × dry weight) = 250 + (0.80 × 250) = 250 + 200 = 450 kg.", difficulty: "intermediate", tags: ["wet-pickup-calc"] },
];
