SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'basic', 'multiple_choice', 'What is the ''flyer'' mechanism on a simplex (speed frame) responsible for?', '["Inserting a light twist into the roving as it''s wound onto the bobbin, guiding it via a rotating arm with a guide eye","Cleaning raw cotton bales before carding","Winding finished yarn onto large cones","Removing trash particles from the licker-in zone of a card"]'::jsonb, 'Inserting a light twist into the roving as it''s wound onto the bobbin, guiding it via a rotating arm with a guide eye', 'The flyer is a rotating arm with a guide eye that both inserts a small amount of protective twist into the drafted strand and guides it onto the roving bobbin, coordinated with a differential motion that controls bobbin speed as it fills.', 1, '{"simplex-flyer"}'::text[]),
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'intermediate', 'multiple_choice', 'Why does a simplex (speed frame) bobbin need a ''differential motion'' (a gear mechanism that gradually changes bobbin speed relative to the flyer as the bobbin fills)?', '["As the bobbin''s effective winding diameter increases with each layer, its rotational speed must be continuously adjusted relative to the flyer to maintain constant roving delivery speed and consistent, correctly tensioned winding","Differential motion exists only to change roving color partway through winding","Bobbin speed never needs to change throughout the entire winding process","The differential motion''s only function is to stop the machine automatically when the bobbin is empty"]'::jsonb, 'As the bobbin''s effective winding diameter increases with each layer, its rotational speed must be continuously adjusted relative to the flyer to maintain constant roving delivery speed and consistent, correctly tensioned winding', 'As roving builds up in layers on the bobbin, its effective diameter grows, which would cause winding speed (and therefore tension) to change if the bobbin rotated at a fixed relationship to the flyer; the differential motion continuously compensates for this changing diameter to maintain consistent delivery speed and winding tension throughout the whole bobbin build.', 2, '{"differential-motion","simplex"}'::text[]),
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'intermediate', 'multiple_choice', 'What does ''yarn realization'' (or ''spinning efficiency of raw material'') generally refer to in a spinning mill''s cost/material accounting?', '["The percentage of raw fiber input that ends up as usable, saleable finished yarn, after accounting for waste at each processing stage","The exact twist level achieved in the final yarn","The color grade of the finished yarn","The total electrical power consumed per kilogram of yarn produced"]'::jsonb, 'The percentage of raw fiber input that ends up as usable, saleable finished yarn, after accounting for waste at each processing stage', 'Yarn realization % tracks how much of the original raw fiber weight is ultimately converted into sellable finished yarn, after unavoidable process waste (trash removal, noil from combing, sweepings, etc.) at each stage — an important cost/efficiency metric for spinning mill management.', 2, '{"yarn-realization"}'::text[]),
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'intermediate', 'multiple_choice', 'Why does combed yarn generally have a LOWER yarn realization percentage than carded yarn made from the same raw cotton?', '["Combing deliberately removes additional short fiber (noil) as waste to improve quality, reducing the proportion of the original raw fiber that ends up in the finished yarn","Combed yarn always has a higher realization percentage than carded yarn, with no exceptions","Yarn realization percentage is identical regardless of whether combing is used","Noil removed during combing is always recycled back into the same yarn immediately, so realization is unaffected"]'::jsonb, 'Combing deliberately removes additional short fiber (noil) as waste to improve quality, reducing the proportion of the original raw fiber that ends up in the finished yarn', 'Since combing intentionally removes short fibers/noil as a separate waste stream (used for other purposes but not going into the combed yarn itself), combed yarn production inherently has a lower realization percentage from the original raw cotton than an equivalent carded yarn process that skips this extra fiber removal step.', 2, '{"combing","yarn-realization"}'::text[]);
COMMIT;
