SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'intermediate', 'multiple_choice', 'What is the function of ''apron'' components (top and bottom aprons) in a modern drafting system (e.g., at the ring frame)?', '["They provide additional, close control of fibers in the critical main drafting zone, improving evenness beyond what plain rollers alone would achieve","They apply dye to the fiber strand as it passes through the drafting zone","They insert the final twist into the yarn, replacing the need for a traveler","They wind the finished yarn onto the takeup bobbin"]'::jsonb, 'They provide additional, close control of fibers in the critical main drafting zone, improving evenness beyond what plain rollers alone would achieve', 'Apron-equipped drafting systems use flexible rubber aprons (top and bottom) that extend fiber control further into the main drafting zone than plain rollers alone could achieve, guiding fibers more precisely during the critical attenuation stage and improving resultant yarn evenness.', 2, '{"drafting-aprons"}'::text[]),
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'intermediate', 'multiple_choice', 'What could happen to yarn evenness if drafting aprons become worn, glazed (hardened/smooth), or damaged over time without replacement?', '["Reduced fiber control in the main drafting zone, leading to increased drafting irregularity and poorer yarn evenness","Worn aprons would have no effect on drafting quality whatsoever","Yarn evenness would automatically improve as aprons wear down","Apron condition only affects yarn color, not evenness"]'::jsonb, 'Reduced fiber control in the main drafting zone, leading to increased drafting irregularity and poorer yarn evenness', 'As aprons wear, glaze, or become damaged, their grip/control over fibers in the drafting zone deteriorates, allowing more uncontrolled fiber movement (similar to the ''floating fiber'' problem) — directly increasing drafting irregularity and reducing yarn evenness, hence periodic apron inspection/replacement is part of routine spinning maintenance.', 2, '{"apron-wear"}'::text[]),
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'basic', 'multiple_choice', 'What is a ''spindle tape'' (or tangential band drive) used for on a conventional ring frame?', '["Transmitting rotational drive power from a central tin roller/motor to each individual spindle via a continuous belt/tape","Applying twist directly without any spindle rotation at all","Measuring the exact twist level of the finished yarn","Cleaning the ring and traveler during operation"]'::jsonb, 'Transmitting rotational drive power from a central tin roller/motor to each individual spindle via a continuous belt/tape', 'A tangential drive tape (spindle tape) runs along a row of spindles, using friction contact with each spindle''s whorl to transmit rotational power from a central drive source (tin roller) — a traditional, still widely used method of powering large numbers of spindles simultaneously on a ring frame.', 1, '{"spindle-tape-drive"}'::text[]),
('9dc3ade3-26ea-41fa-a83f-95a7440889b8', 'intermediate', 'multiple_choice', 'What does ''individual spindle drive'' (as opposed to shared tangential tape drive) offer as a potential advantage on modern ring frames?', '["The ability to control/vary each spindle''s speed independently, useful for advanced process optimization, energy savings, or handling yarn breaks without stopping the whole machine","Individual spindle drive completely eliminates the need for any twist insertion","It only works for synthetic filament yarn, never for staple-spun yarn","It removes the need for any traveler or ring at all"]'::jsonb, 'The ability to control/vary each spindle''s speed independently, useful for advanced process optimization, energy savings, or handling yarn breaks without stopping the whole machine', 'Individual (often electronically controlled) spindle drives allow each spindle''s speed to be adjusted independently — enabling advanced features like gradual speed ramp-up/down for reduced breakage, energy-saving idle modes for stopped positions, and finer process optimization than a single shared tangential drive allows.', 2, '{"individual-spindle-drive"}'::text[]);
COMMIT;
