SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'What is a ''circular loom'' typically used for producing?', '["Tubular or seamless woven fabric (like sacks/bags for packaging) by weaving warp arranged in a circular formation","Only flat, open-width fabric identical to a standard shuttle loom''s output","Fabric that must always be cut open immediately after weaving, with no tubular use case","A loom exclusively used for jacquard pattern weaving, unrelated to tube shapes"]'::jsonb, 'Tubular or seamless woven fabric (like sacks/bags for packaging) by weaving warp arranged in a circular formation', 'Circular looms arrange warp yarns around a circular path and weave weft continuously around that circle, producing seamless tubular fabric — widely used for woven polypropylene sacks/bags used in bulk packaging (e.g., rice, cement, grain).', 1, '{"circular-loom"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'What is ''narrow fabric weaving'' (needle looms, narrow-width shuttle looms) typically used to produce?', '["Ribbons, tapes, webbing, labels, and other narrow-width woven items rather than wide, garment-scale fabric","Only extremely wide fabric used for bedsheets","Fabric that can never include any woven-in pattern or logo","A method used exclusively for producing denim fabric"]'::jsonb, 'Ribbons, tapes, webbing, labels, and other narrow-width woven items rather than wide, garment-scale fabric', 'Narrow fabric looms (needle looms and similar) are specialized for producing narrow-width woven products like ribbons, tapes, webbing, and woven labels — a distinct product category from wide-width apparel/home-textile fabric.', 1, '{"narrow-fabric-weaving"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'What is a ''triaxial weave'' (a specialized, less common weaving structure)?', '["A structure using THREE yarn systems interlacing at roughly 60° angles to each other, rather than the usual two systems (warp/weft) at 90°","A synonym for standard plain weave with no structural difference","A weave that uses no warp yarn system at all, only weft","A weave that can only be produced using natural fiber, never synthetic"]'::jsonb, 'A structure using THREE yarn systems interlacing at roughly 60° angles to each other, rather than the usual two systems (warp/weft) at 90°', 'Triaxial weaving interlaces three yarn systems at approximately 60-degree angles to one another (rather than the conventional two-system 90-degree warp/weft structure), producing a fabric with more balanced multi-directional strength/stability, used in specialized technical textile applications.', 2, '{"triaxial-weave"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'Why might a technical/industrial application (e.g., certain composite reinforcement fabrics) prefer a triaxial weave over standard biaxial (warp/weft) weave?', '["Triaxial structure provides more balanced strength/stability across multiple directions (not just the two perpendicular axes), useful where multi-directional load resistance matters","Triaxial weave is always cheaper to produce than any standard biaxial weave","Triaxial weave cannot be used in any technical or industrial application, only decorative textiles","Biaxial weave always provides superior multi-directional strength compared to triaxial weave"]'::jsonb, 'Triaxial structure provides more balanced strength/stability across multiple directions (not just the two perpendicular axes), useful where multi-directional load resistance matters', 'Because triaxial weave distributes yarn systems across three directions rather than just two perpendicular ones, it can offer more balanced strength and resistance to shear/distortion from multiple directions — valuable in certain technical textile/composite reinforcement applications where multi-directional stability matters more than in typical apparel fabric.', 2, '{"triaxial-weave-application"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'What does ''fabric GSM per yarn count relationship'' generally imply: for the SAME weave construction and thread density, using a COARSER yarn count typically results in what GSM change?', '["Higher GSM (heavier fabric), since coarser yarn carries more mass per unit length in the same fabric area","Lower GSM, since coarser yarn always weighs less than finer yarn","No change in GSM, since yarn count has no relationship to fabric weight","GSM becomes impossible to calculate once yarn count changes"]'::jsonb, 'Higher GSM (heavier fabric), since coarser yarn carries more mass per unit length in the same fabric area', 'For the same thread density (EPI/PPI) and weave, switching to a coarser (thicker, more mass-per-length) yarn directly increases the total fiber mass packed into the same fabric area, raising the resulting GSM — a direct, predictable relationship used in fabric engineering/costing calculations.', 2, '{"gsm-yarn-count-relationship"}'::text[]);
COMMIT;
