SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'A reed has 60 dents per inch, and 2 warp ends are drawn through each dent. What is the resulting ends per inch (EPI) of the warp?', '["120 EPI","60 EPI","30 EPI","62 EPI"]'::jsonb, '120 EPI', 'EPI = reed count (dents per inch) × ends drawn per dent = 60 × 2 = 120 EPI.', 1, '{"epi-calculation"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'A reed has 40 dents per inch, and 3 warp ends are drawn through each dent. What is the resulting ends per inch (EPI) of the warp?', '["120 EPI","40 EPI","13.3 EPI","43 EPI"]'::jsonb, '120 EPI', 'EPI = reed count × ends per dent = 40 × 3 = 120 EPI.', 1, '{"epi-calculation"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'A fabric has 100 EPI (ends per inch) and 80 PPI (picks per inch), both using 40s Ne yarn. Which statement about this fabric''s construction is correct regarding its thread balance?', '["The fabric has more warp density than weft density (EPI > PPI), typical of many standard shirting fabrics","The fabric has more weft density than warp density in this case","EPI and PPI are exactly equal, indicating a perfectly balanced construction","This combination is impossible for any woven fabric to have"]'::jsonb, 'The fabric has more warp density than weft density (EPI > PPI), typical of many standard shirting fabrics', 'Since EPI (100) is greater than PPI (80), the fabric has a higher warp thread density than weft thread density — a common, valid construction pattern (not perfectly square/balanced) seen in many standard fabrics.', 1, '{"epi-ppi-comparison"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A fabric requires 3.2 meters of warp yarn (including take-up allowance) to produce 3.0 meters of finished fabric length. Using take-up % expressed relative to the finished fabric length, what is the approximate warp take-up percentage?', '["≈ 6.67%","≈ 3.2%","≈ 93.75%","≈ 20%"]'::jsonb, '≈ 6.67%', 'Take-up %, expressed relative to finished fabric length, = ((warp length consumed − fabric length produced) / fabric length produced) × 100 = ((3.2 − 3.0) / 3.0) × 100 ≈ 6.67%.', 2, '{"warp-takeup-calc"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A weaving order requires 5,000 meters of finished fabric. If warp take-up is 5% (meaning 5% extra warp length is needed beyond the finished fabric length), approximately how much warp yarn length must be prepared?', '["≈ 5,250 meters","≈ 5,000 meters","≈ 4,750 meters","≈ 5,500 meters"]'::jsonb, '≈ 5,250 meters', 'Required warp length = fabric length × (1 + take-up%) = 5,000 × 1.05 = 5,250 meters.', 2, '{"warp-length-calc"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A weaving order requires 8,000 meters of finished fabric. If warp take-up is 8%, approximately how much warp yarn length must be prepared?', '["≈ 8,640 meters","≈ 8,000 meters","≈ 7,360 meters","≈ 8,800 meters"]'::jsonb, '≈ 8,640 meters', 'Required warp length = fabric length × (1 + take-up%) = 8,000 × 1.08 = 8,640 meters.', 2, '{"warp-length-calc"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A fabric is designed with 110 EPI, 70 PPI, warp yarn 30s Ne, and weft yarn 24s Ne. Which single factor would you need in ADDITION to these to calculate the fabric''s cover factor?', '["No additional factor is needed — cover factor is calculated directly from thread density (EPI/PPI) and yarn count (which determines yarn diameter)","The exact dye color used on the fabric","The total order quantity in meters","The fabric''s final selling price"]'::jsonb, 'No additional factor is needed — cover factor is calculated directly from thread density (EPI/PPI) and yarn count (which determines yarn diameter)', 'Cover factor is calculated purely from thread density (EPI/PPI) and yarn count (which determines the yarn''s effective diameter) — no other production or commercial factor (color, price, quantity) is needed for this specific calculation.', 2, '{"cover-factor-inputs"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'A fabric sample measuring exactly 1 square meter is found to weigh 150 grams. What is this fabric''s GSM (grams per square meter)?', '["150 GSM","1.5 GSM","15,000 GSM","0.15 GSM"]'::jsonb, '150 GSM', 'GSM is literally grams per square meter; a 1 sq. meter sample weighing 150 g has a GSM of 150.', 1, '{"gsm-calculation"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'A fabric sample measuring 0.5 square meters is found to weigh 90 grams. What is this fabric''s GSM (grams per square meter)?', '["180 GSM","90 GSM","45 GSM","450 GSM"]'::jsonb, '180 GSM', 'GSM = weight (g) / area (m²) = 90 / 0.5 = 180 GSM.', 1, '{"gsm-calculation"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A garment order needs 12,000 meters of fabric at 1.5 meters usable width. If the fabric GSM is 200, what is the approximate total fabric weight required, in kilograms?', '["≈ 3,600 kg","≈ 2,400 kg","≈ 1,800 kg","≈ 4,800 kg"]'::jsonb, '≈ 3,600 kg', 'Total weight (kg) = length (m) × width (m) × GSM (g/m²) / 1000 = 12,000 × 1.5 × 200 / 1000 = 3,600,000 g / 1000 = 3,600 kg.', 2, '{"fabric-weight-calc"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A garment order needs 8,000 meters of fabric at 1.6 meters usable width. If the fabric GSM is 180, what is the approximate total fabric weight required, in kilograms?', '["≈ 2,304 kg","≈ 1,440 kg","≈ 1,800 kg","≈ 2,880 kg"]'::jsonb, '≈ 2,304 kg', 'Total weight (kg) = length × width × GSM / 1000 = 8,000 × 1.6 × 180 / 1000 = 2,304,000 g / 1000 = 2,304 kg.', 2, '{"fabric-weight-calc"}'::text[]);
COMMIT;
