SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'What is ''warping'' (or beaming) in fabric production?', '["The process of winding many individual warp yarns from a creel of bobbins/cones onto a warp beam in parallel, under uniform tension","The process of inserting weft yarn into the shed","The finishing process applied to fabric after weaving","The process of dyeing yarn before it is woven"]'::jsonb, 'The process of winding many individual warp yarns from a creel of bobbins/cones onto a warp beam in parallel, under uniform tension', 'Warping combines hundreds or thousands of individual yarn ends from a creel and winds them in parallel, under controlled uniform tension, onto a warp beam ready for sizing and weaving.', 1, '{"warping"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'What is ''drawing-in'' in loom preparation?', '["Threading each warp yarn through its correct heald eye and reed dent according to the weave design and pattern draft","Winding the finished fabric onto the cloth roller","Applying size/starch to the warp yarn","Cutting the warp yarn to the correct loom length"]'::jsonb, 'Threading each warp yarn through its correct heald eye and reed dent according to the weave design and pattern draft', 'Drawing-in threads each individual warp end through the correct heald (on the correct frame, per the weave''s draft plan) and then through the correct reed dent — essential setup before weaving can begin on a new warp.', 1, '{"drawing-in"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'Why must warp yarns be uniformly tensioned during warping, before weaving even begins?', '["Uneven tension at the warping stage carries through to weaving, causing some threads to be looser/tighter than others and creating fabric defects","Tension during warping has no effect on the later weaving process","Warping tension only affects the fabric''s final color","Uniform tension is only relevant for synthetic yarns, not natural fibers"]'::jsonb, 'Uneven tension at the warping stage carries through to weaving, causing some threads to be looser/tighter than others and creating fabric defects', 'If warp threads are wound at inconsistent tension during warping, that inconsistency persists on the beam and through weaving — looser threads sag and may not interlace properly while tighter ones may break more easily, both causing fabric defects.', 2, '{"warping-tension"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'What is a ''pirn'' in traditional shuttle weaving?', '["A small tapered bobbin holding weft yarn, inserted into the shuttle","The large beam holding warp yarn","The comb-like device that spaces warp yarns","The mechanism that raises and lowers healds"]'::jsonb, 'A small tapered bobbin holding weft yarn, inserted into the shuttle', 'A pirn is a small, often tapered, weft package that fits inside the shuttle; as the shuttle travels across the shed, weft yarn unwinds from the pirn to form each pick.', 1, '{"pirn","shuttle-weaving"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'What is the general relationship between loom weft-insertion speed and achievable fabric width for shuttleless weft insertion methods like air-jet?', '["Very high insertion speeds are harder to maintain reliably as fabric width increases, since the weft must travel farther in the same available time","Fabric width has no relationship to weft insertion reliability at any speed","Wider fabrics always weave faster than narrower ones on the same loom type","Weft insertion speed is completely independent of loom width by design"]'::jsonb, 'Very high insertion speeds are harder to maintain reliably as fabric width increases, since the weft must travel farther in the same available time', 'For a fixed loom cycle time, a wider fabric requires the weft to travel a longer distance across the shed; maintaining reliable, controlled insertion (especially for air-jet, which relies on airflow control) becomes more challenging as width increases, often requiring relay nozzles to assist.', 2, '{"weft-insertion","loom-width"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'What is the main purpose of ''healds'' being organized onto multiple separate frames (harnesses) rather than all on one frame?', '["To allow different groups of warp threads to be raised/lowered independently, enabling weave patterns beyond simple plain weave","Multiple frames exist purely to reduce the total number of healds needed","Frames have no functional purpose and are purely a historical convention","A single frame could always produce any weave pattern equally well"]'::jsonb, 'To allow different groups of warp threads to be raised/lowered independently, enabling weave patterns beyond simple plain weave', 'Since each frame moves as a single unit, using multiple frames (each threaded with a specific subset of warp yarns) allows different interlacing sequences pick-to-pick — the basis for producing twill, satin, and other pattern weaves beyond simple plain weave (which needs only 2 frames).', 1, '{"heald-frames","weave-design"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'basic', 'multiple_choice', 'How many heald frames are minimally needed to weave a basic plain weave fabric?', '["2","1","4","8"]'::jsonb, '2', 'Plain weave requires alternating odd/even warp threads to rise and fall in opposite pattern each pick — this simplest interlacing needs just 2 heald frames (odd threads on one, even threads on the other).', 1, '{"plain-weave","heald-frames"}'::text[]),
('4b495e60-fc2b-4165-a0c7-e0b144e931f7', 'intermediate', 'multiple_choice', 'A 3-up, 1-down twill weave repeat requires a minimum of how many heald frames?', '["4","2","8","1"]'::jsonb, '4', 'A twill weave''s minimum heald-frame requirement equals its repeat size; a 3-up-1-down twill has a 4-thread repeat (3 warp floats over + 1 interlacing point), requiring 4 frames to control the sequential offsetting pattern.', 2, '{"twill-weave","heald-frames"}'::text[]);
COMMIT;
