module.exports = [
{ q: "A fabric's greige (unprocessed) weight is 100 kg, and after wet processing (scouring, bleaching, dyeing) it weighs 95 kg. What is the approximate processing weight loss percentage?", options: ["5%", "95%", "100%", "0.95%"], correct: "5%", exp: "Weight loss % = ((greige weight − finished weight) / greige weight) × 100 = ((100 − 95) / 100) × 100 = 5%.", difficulty: "basic", tags: ["processing-weight-loss-calc"] },
{ q: "A fabric's greige weight is 500 kg, and after wet processing it weighs 465 kg. What is the approximate processing weight loss percentage?", options: ["7%", "93%", "35%", "0.7%"], correct: "7%", exp: "Weight loss % = ((500 − 465) / 500) × 100 = (35/500) × 100 = 7%.", difficulty: "basic", tags: ["processing-weight-loss-calc"] },
{ q: "A fabric measures 1.60 meters wide before finishing (stentering), and after the stenter sets it to a controlled final width, it measures 1.52 meters. What is the approximate width shrinkage percentage?", options: ["5%", "1.52%", "8%", "95%"], correct: "5%", exp: "Width shrinkage % = ((initial width − final width) / initial width) × 100 = ((1.60 − 1.52) / 1.60) × 100 = 5%.", difficulty: "intermediate", tags: ["width-shrinkage-calc"] },
{ q: "A fabric measures 1.70 meters wide before finishing, and after processing measures 1.53 meters. What is the approximate width shrinkage percentage?", options: ["10%", "1.53%", "17%", "90%"], correct: "10%", exp: "Width shrinkage % = ((1.70 − 1.53) / 1.70) × 100 = (0.17/1.70) × 100 = 10%.", difficulty: "intermediate", tags: ["width-shrinkage-calc"] },
{ q: "An ETP (effluent treatment plant) processes 2,000 liters of wastewater per hour and operates 20 hours per day. What is the approximate total daily wastewater treatment volume?", options: ["40,000 liters", "2,000 liters", "20,000 liters", "100 liters"], correct: "40,000 liters", exp: "Daily volume = flow rate per hour × operating hours = 2,000 L/hr × 20 hr = 40,000 liters.", difficulty: "basic", tags: ["etp-volume-calc"] },
{ q: "An ETP processes 3,500 liters of wastewater per hour and operates 16 hours per day. What is the approximate total daily wastewater treatment volume?", options: ["56,000 liters", "3,500 liters", "16,000 liters", "219 liters"], correct: "56,000 liters", exp: "Daily volume = flow rate per hour × operating hours = 3,500 L/hr × 16 hr = 56,000 liters.", difficulty: "basic", tags: ["etp-volume-calc"] },
{ q: "A dyeing machine's water consumption is 15 liters per kg of fabric processed. For a 1,200 kg fabric batch, what is the approximate total water consumption?", options: ["18,000 liters", "1,200 liters", "15 liters", "80 liters"], correct: "18,000 liters", exp: "Total water = consumption rate per kg × fabric weight = 15 L/kg × 1,200 kg = 18,000 liters.", difficulty: "basic", tags: ["water-consumption-calc"] },
{ q: "A dyeing machine's water consumption is 20 liters per kg of fabric processed. For a 900 kg fabric batch, what is the approximate total water consumption?", options: ["18,000 liters", "900 liters", "20 liters", "45 liters"], correct: "18,000 liters", exp: "Total water = consumption rate per kg × fabric weight = 20 L/kg × 900 kg = 18,000 liters.", difficulty: "basic", tags: ["water-consumption-calc"] },
];
