SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'What is ''combined scouring-bleaching'' (a one-bath process) intended to achieve compared to running scouring and bleaching as two entirely separate baths?', '["Saving time, water, and energy by performing both cleaning functions together in a single processing bath/cycle","Combined processing always produces worse results than doing each step completely separately","There is no possible way to combine these two processes in any single bath","Combined scouring-bleaching eliminates the need for any subsequent dyeing step"]'::jsonb, 'Saving time, water, and energy by performing both cleaning functions together in a single processing bath/cycle', 'Where compatible chemistry allows, combining scouring and bleaching into a single bath/cycle (rather than two fully separate processes with their own heating/rinsing) saves significant processing time, water, and energy — an efficiency improvement many mills adopt when fabric/quality requirements permit it.', 2, '{"combined-scour-bleach"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'basic', 'multiple_choice', 'What does ''whiteness index'' quantify for bleached textile material?', '["A numerical measure of how white a bleached fabric appears, based on its light reflectance characteristics, used to evaluate/compare bleaching effectiveness","The exact percentage of synthetic fiber in a blended fabric","The total weight of chemicals used during the bleaching process","The exact twist level of yarn used in the fabric"]'::jsonb, 'A numerical measure of how white a bleached fabric appears, based on its light reflectance characteristics, used to evaluate/compare bleaching effectiveness', 'Whiteness index is a standardized numerical value (calculated from spectrophotometric reflectance measurements) that quantifies perceived whiteness, allowing objective comparison of bleaching results between batches or against a target specification.', 1, '{"whiteness-index"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'What is an ''optical brightening agent'' (OBA/fluorescent whitening agent) sometimes applied after bleaching to further enhance perceived whiteness?', '["A chemical that absorbs invisible UV light and re-emits it as visible blue light, optically counteracting yellow undertones to make fabric appear brighter/whiter","A chemical that physically removes all remaining natural pigment via oxidation, unrelated to any light-emission effect","A pigment that adds a visible blue dye color to the fabric permanently, unrelated to any UV interaction","A finishing chemical that has no relationship to how the human eye perceives whiteness"]'::jsonb, 'A chemical that absorbs invisible UV light and re-emits it as visible blue light, optically counteracting yellow undertones to make fabric appear brighter/whiter', 'OBAs work through fluorescence: they absorb invisible ultraviolet light and re-emit it as visible blue light, which optically counteracts the yellowish undertone that remains in most bleached fabric, making it appear noticeably brighter/whiter to the human eye than bleaching chemistry alone would achieve.', 2, '{"optical-brightening-agent"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'Why might a fabric treated with optical brightening agents appear to glow or look unusually bright under a UV/blacklight source (e.g., at a nightclub or under certain inspection lights)?', '["The OBA is actively absorbing UV light and re-emitting it as visible light, an effect that becomes very pronounced under UV-rich blacklight illumination","OBA-treated fabric contains radioactive materials that always glow under any light","This glowing effect only happens with natural fiber, never with any treated fabric","UV light has no interaction whatsoever with optical brightening agents"]'::jsonb, 'The OBA is actively absorbing UV light and re-emitting it as visible light, an effect that becomes very pronounced under UV-rich blacklight illumination', 'Since blacklights emit concentrated UV light (with little visible light), OBA-treated fabric''s fluorescence effect (absorbing UV, re-emitting visible blue light) becomes strikingly visible/pronounced — the same phenomenon that makes some white clothing ''glow'' distinctly under blacklight/UV inspection.', 2, '{"optical-brightener-uv-effect"}'::text[]);
COMMIT;
