module.exports = [
{ q: "A sewing line has 30 operators, each working an 8-hour (480-minute) shift. If a garment's SAM is 12 minutes, what is the line's theoretical maximum daily output (at 100% efficiency)?", options: ["1,200 garments", "40 garments", "480 garments", "14,400 garments"], correct: "1,200 garments", exp: "Theoretical output = (number of operators × minutes per shift) ÷ SAM = (30 × 480) ÷ 12 = 14,400 ÷ 12 = 1,200 garments.", difficulty: "intermediate", tags: ["line-output-calc"] },
{ q: "A sewing line has 25 operators working an 8-hour shift (480 min), with a garment SAM of 15 minutes. At 80% line efficiency, what is the actual expected daily output?", options: ["640 garments", "800 garments", "500 garments", "960 garments"], correct: "640 garments", exp: "Theoretical output = (25 × 480) ÷ 15 = 12,000 ÷ 15 = 800 garments. At 80% efficiency: 800 × 0.80 = 640 garments.", difficulty: "intermediate", tags: ["line-output-calc"] },
{ q: "A garment's SAM is 18 minutes, and the labor cost rate is $0.05 per minute. What is the approximate labor cost per garment?", options: ["$0.90", "$0.05", "$18.00", "$3.60"], correct: "$0.90", exp: "Labor cost per garment = SAM × cost per minute = 18 × $0.05 = $0.90.", difficulty: "basic", tags: ["labor-cost-calc"] },
{ q: "A garment's SAM is 22 minutes, and the labor cost rate is $0.04 per minute. What is the approximate labor cost per garment?", options: ["$0.88", "$0.04", "$22.00", "$5.50"], correct: "$0.88", exp: "Labor cost per garment = SAM × cost per minute = 22 × $0.04 = $0.88.", difficulty: "basic", tags: ["labor-cost-calc"] },
{ q: "A marker is 3 meters long and uses fabric of 1.5 meters width, giving a total marker area of 4.5 square meters. If the pattern pieces cover 3.6 square meters of that marker, what is the marker efficiency percentage?", options: ["80%", "125%", "75%", "60%"], correct: "80%", exp: "Marker efficiency % = (area covered by pieces / total marker area) × 100 = (3.6 / 4.5) × 100 = 80%.", difficulty: "intermediate", tags: ["marker-efficiency-calc"] },
{ q: "A marker has a total area of 6 square meters, and pattern pieces cover 4.5 square meters of it. What is the marker efficiency percentage?", options: ["75%", "133%", "67%", "90%"], correct: "75%", exp: "Marker efficiency % = (4.5 / 6) × 100 = 75%.", difficulty: "intermediate", tags: ["marker-efficiency-calc"] },
{ q: "A cutting room spreads 80 layers of fabric for one marker of 2.5 meters length. Approximately how many meters of fabric are consumed in this one lay (ignoring end loss)?", options: ["200 meters", "80 meters", "2.5 meters", "32 meters"], correct: "200 meters", exp: "Total fabric in the lay = number of layers × marker length = 80 × 2.5 = 200 meters.", difficulty: "basic", tags: ["lay-consumption-calc"] },
{ q: "A cutting room spreads 120 layers of fabric for one marker of 3.2 meters length. Approximately how many meters of fabric are consumed in this one lay?", options: ["384 meters", "120 meters", "3.2 meters", "37.5 meters"], correct: "384 meters", exp: "Total fabric in the lay = number of layers × marker length = 120 × 3.2 = 384 meters.", difficulty: "basic", tags: ["lay-consumption-calc"] },
{ q: "An AQL inspection samples 125 units from a shipment and finds 4 defective units, against an acceptance number of 5 for that sample size/AQL level. What is the inspection result?", options: ["The shipment PASSES, since 4 defects is at or below the acceptance number of 5", "The shipment automatically FAILS regardless of the acceptance number", "The result is inconclusive and requires re-sampling the entire lot", "AQL results only apply to color defects, not general quality defects"], correct: "The shipment PASSES, since 4 defects is at or below the acceptance number of 5", exp: "In AQL sampling, if the number of defects found is at or below the defined acceptance number for that sample size/AQL level, the lot passes; since 4 is less than the acceptance number of 5, this shipment passes inspection.", difficulty: "basic", tags: ["aql-pass-fail"] },
];
