SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('44444444-4444-4444-4444-444444444444', 'basic', 'multiple_choice', 'What is a ''lining'' in garment construction (e.g., in a jacket)?', '["An inner fabric layer sewn inside a garment to cover raw seams, improve comfort against the skin, and sometimes add structure","The outermost visible fabric layer of a garment","A decorative trim applied to the garment''s exterior","A type of interfacing used only on collars"]'::jsonb, 'An inner fabric layer sewn inside a garment to cover raw seams, improve comfort against the skin, and sometimes add structure', 'Lining is a separate fabric layer sewn to the inside of a garment, hiding raw seam edges/interfacing for a clean finish, improving how the garment feels against skin, and helping the garment retain its shape.', 1, '{"garment-lining"}'::text[]),
('44444444-4444-4444-4444-444444444444', 'intermediate', 'multiple_choice', 'What is ''underlining'' different from regular ''lining'' in garment construction?', '["Underlining is cut to match the outer fabric shape and is attached to the WRONG side of the outer fabric BEFORE construction (adding body/support), while lining is a separate inner layer added after","Underlining and lining are identical terms with zero distinction","Underlining is always visible from the garment''s right side, while lining is always hidden","Underlining only applies to sleeves, never to the main body of a garment"]'::jsonb, 'Underlining is cut to match the outer fabric shape and is attached to the WRONG side of the outer fabric BEFORE construction (adding body/support), while lining is a separate inner layer added after', 'Underlining is basted/attached to the back of the outer (fashion) fabric before the garment is assembled, functioning as one combined layer that adds body, support, or opacity — distinct from lining, which is constructed as its own separate inner layer and attached afterward, mainly for a clean interior finish.', 2, '{"underlining-vs-lining"}'::text[]),
('44444444-4444-4444-4444-444444444444', 'basic', 'multiple_choice', 'What is ''interfacing'' used for in garment construction (distinct from interlining)?', '["Adding structure, shape retention, and stability to specific garment areas like collars, cuffs, and waistbands","Providing warmth as a thick insulating layer, like a winter coat''s interlining","A decorative outer fabric layer visible on the garment''s exterior","A type of closure used instead of buttons or zippers"]'::jsonb, 'Adding structure, shape retention, and stability to specific garment areas like collars, cuffs, and waistbands', 'Interfacing (often fusible) is applied to specific structural areas — collars, cuffs, waistbands, plackets — to add crispness, shape retention, and stability, preventing those areas from sagging or losing form during wear.', 1, '{"interfacing"}'::text[]),
('44444444-4444-4444-4444-444444444444', 'intermediate', 'multiple_choice', 'What is the functional difference between ''interfacing'' and ''interlining'' in garment construction?', '["Interfacing adds structure/stability to specific small areas (collars, cuffs), while interlining is typically a full inner layer added mainly for warmth/insulation (like in winter coats)","Interfacing and interlining are exactly the same thing, just different regional terms with zero functional difference","Interlining is used only for structure, never for warmth","Interfacing is applied to an entire garment''s full body, never to small areas"]'::jsonb, 'Interfacing adds structure/stability to specific small areas (collars, cuffs), while interlining is typically a full inner layer added mainly for warmth/insulation (like in winter coats)', 'Interfacing is typically applied to specific structural points needing stability (collars, cuffs, waistbands), while interlining is usually a fuller inner layer (like batting or fleece) added between the outer fabric and lining primarily for warmth/insulation — two related but functionally distinct construction elements.', 2, '{"interfacing-vs-interlining"}'::text[]),
('44444444-4444-4444-4444-444444444444', 'basic', 'multiple_choice', 'What is a ''facing'' in garment construction (e.g., a neckline facing)?', '["A shaped fabric piece attached to finish a raw edge (like a neckline or armhole) by folding it to the inside, hidden from view","A decorative appliqué sewn onto the garment''s front","The outermost fashion fabric layer of the entire garment","A type of button closure"]'::jsonb, 'A shaped fabric piece attached to finish a raw edge (like a neckline or armhole) by folding it to the inside, hidden from view', 'A facing is a shaped fabric piece (matching the edge it finishes) sewn to a raw edge like a neckline or armhole, then folded to the garment''s inside, giving a clean, finished edge without needing a full lining.', 1, '{"garment-facing"}'::text[]);
COMMIT;
