module.exports = [
{ q: "A dyeing recipe calls for 2.5% owf of a reactive dye. For a batch of 350 kg fabric, how many kg of dye are needed?", options: ["8.75 kg", "2.5 kg", "35 kg", "0.875 kg"], correct: "8.75 kg", exp: "Dye needed = %owf × fabric weight = 0.025 × 350 kg = 8.75 kg.", difficulty: "basic", tags: ["dye-recipe-calc"] },
{ q: "A dyeing recipe calls for 0.8% owf of a reactive dye. For a batch of 1,200 kg fabric, how many kg of dye are needed?", options: ["9.6 kg", "0.8 kg", "96 kg", "15 kg"], correct: "9.6 kg", exp: "Dye needed = %owf × fabric weight = 0.008 × 1,200 kg = 9.6 kg.", difficulty: "basic", tags: ["dye-recipe-calc"] },
{ q: "A dyeing machine uses a liquor ratio of 1:6 for a 700 kg fabric batch. How many liters of dye liquor are needed?", options: ["4,200 liters", "700 liters", "116.7 liters", "6 liters"], correct: "4,200 liters", exp: "Liquor volume = liquor ratio × fabric weight = 6 × 700 kg = 4,200 liters.", difficulty: "basic", tags: ["liquor-ratio-calc"] },
{ q: "A dyeing machine uses a liquor ratio of 1:15 for a 150 kg fabric batch. How many liters of dye liquor are needed?", options: ["2,250 liters", "150 liters", "10 liters", "15 liters"], correct: "2,250 liters", exp: "Liquor volume = liquor ratio × fabric weight = 15 × 150 kg = 2,250 liters.", difficulty: "basic", tags: ["liquor-ratio-calc"] },
{ q: "A recipe requires 50 g/L of salt at a liquor ratio of 1:8 for a 400 kg fabric batch. How many kg of salt are needed?", options: ["160 kg", "50 kg", "8 kg", "400 kg"], correct: "160 kg", exp: "Total liquor = 8 × 400 kg = 3,200 liters. Total salt = 50 g/L × 3,200 L = 160,000 g = 160 kg.", difficulty: "intermediate", tags: ["salt-dosing-calc"] },
{ q: "A recipe requires 65 g/L of soda ash at a liquor ratio of 1:10 for a 300 kg fabric batch. How many kg of soda ash are needed?", options: ["195 kg", "65 kg", "10 kg", "300 kg"], correct: "195 kg", exp: "Total liquor = 10 × 300 kg = 3,000 liters. Total soda ash = 65 g/L × 3,000 L = 195,000 g = 195 kg.", difficulty: "intermediate", tags: ["alkali-dosing-calc"] },
{ q: "A dye bath achieves 88% exhaustion for a recipe using 2.5% owf dye on a 500 kg fabric batch. Approximately how much dye (in kg) remains unexhausted?", options: ["≈ 1.5 kg", "≈ 12.5 kg", "≈ 11 kg", "≈ 2.5 kg"], correct: "≈ 1.5 kg", exp: "Total dye = 0.025 × 500 kg = 12.5 kg. Exhausted = 88% of 12.5 kg = 11 kg. Unexhausted = 12.5 − 11 = 1.5 kg.", difficulty: "intermediate", tags: ["dye-exhaustion-calc"] },
{ q: "A dye bath achieves 90% exhaustion for a recipe using 1.8% owf dye on a 800 kg fabric batch. Approximately how much dye (in kg) remains unexhausted?", options: ["≈ 1.44 kg", "≈ 14.4 kg", "≈ 12.96 kg", "≈ 1.8 kg"], correct: "≈ 1.44 kg", exp: "Total dye = 0.018 × 800 kg = 14.4 kg. Exhausted = 90% of 14.4 kg = 12.96 kg. Unexhausted = 14.4 − 12.96 = 1.44 kg.", difficulty: "intermediate", tags: ["dye-exhaustion-calc"] },
{ q: "A fabric's greige weight is 300 kg, and after wet processing it weighs 279 kg. What is the approximate processing weight loss percentage?", options: ["7%", "93%", "21%", "2.7%"], correct: "7%", exp: "Weight loss % = ((greige weight − finished weight) / greige weight) × 100 = ((300 − 279) / 300) × 100 = 7%.", difficulty: "basic", tags: ["processing-weight-loss-calc"] },
{ q: "A fabric's greige weight is 900 kg, and after wet processing it weighs 828 kg. What is the approximate processing weight loss percentage?", options: ["8%", "92%", "72%", "0.8%"], correct: "8%", exp: "Weight loss % = ((900 − 828) / 900) × 100 = (72/900) × 100 = 8%.", difficulty: "basic", tags: ["processing-weight-loss-calc"] },
{ q: "A padder shows 68% wet pickup. For 500 kg of dry fabric entering the padder, what is the total wet weight after padding?", options: ["840 kg", "500 kg", "340 kg", "568 kg"], correct: "840 kg", exp: "Wet weight = dry weight × (1 + wet pickup%) = 500 × 1.68 = 840 kg.", difficulty: "intermediate", tags: ["wet-pickup-calc"] },
{ q: "A padder shows 72% wet pickup. For 250 kg of dry fabric entering the padder, what is the total wet weight after padding?", options: ["430 kg", "250 kg", "180 kg", "322 kg"], correct: "430 kg", exp: "Wet weight = dry weight × (1 + wet pickup%) = 250 × 1.72 = 430 kg.", difficulty: "intermediate", tags: ["wet-pickup-calc"] },
];
