SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('33333333-3333-3333-3333-333333333333', 'basic', 'multiple_choice', 'What is ''continuous bleaching range'' equipment designed for, compared to batch (exhaust) bleaching?', '["Processing fabric in open-width form at high speed through a continuous sequence of chemical application, steaming/reaction, and washing, suited to large-volume production","A machine used only for small lab-scale sample bleaching","Equipment that can only process loose fiber, never fabric","A machine that replaces the need for hydrogen peroxide entirely"]'::jsonb, 'Processing fabric in open-width form at high speed through a continuous sequence of chemical application, steaming/reaction, and washing, suited to large-volume production', 'A continuous bleaching range moves fabric through a sequence of stages (chemical application, steaming for reaction time, washing) at high speed in open-width form — efficient for high-volume production compared to processing fabric in discrete batches.', 1, '{"continuous-bleaching"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'What is a ''J-box'' used for in a continuous bleaching/scouring range?', '["Providing a dwell/reaction time chamber (shaped like a J) where fabric accumulates in loose folds to allow chemical reactions to complete before the next stage","A storage box for finished, folded garments","A machine used to measure fabric width only","A device used exclusively for cutting fabric rolls into shorter lengths"]'::jsonb, 'Providing a dwell/reaction time chamber (shaped like a J) where fabric accumulates in loose folds to allow chemical reactions to complete before the next stage', 'A J-box is a J-shaped storage/reaction chamber where fabric accumulates in relaxed folds after chemical application, giving it the necessary dwell time for the scouring/bleaching reaction to complete before moving to the next processing stage — a common component in continuous ranges.', 2, '{"j-box"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'What is the purpose of a ''squeezing mangle'' positioned between stages in a continuous processing range?', '["Removing excess liquor before the next stage, controlling carryover and preventing dilution of the next bath''s chemistry","Applying the initial dye color to the fabric","Measuring the exact fabric length processed so far","Cutting fabric into shorter pieces between stages"]'::jsonb, 'Removing excess liquor before the next stage, controlling carryover and preventing dilution of the next bath''s chemistry', 'Between processing stages, squeeze mangles remove excess liquor from the fabric so it doesn''t carry over into and dilute/contaminate the next stage''s fresh chemical bath — maintaining consistent, controlled chemistry at each stage.', 2, '{"squeeze-mangle-between-stages"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'Why is consistent fabric tension control important throughout a continuous processing range?', '["Inconsistent tension can cause uneven stretching, width variation, or fabric distortion as it passes through the many stages of the range","Tension control has no measurable effect on fabric quality during continuous processing","Continuous ranges never apply any tension to the fabric at all","Tension only matters at the very final stage, not throughout the range"]'::jsonb, 'Inconsistent tension can cause uneven stretching, width variation, or fabric distortion as it passes through the many stages of the range', 'As fabric passes through many rollers and stages in a continuous range, inconsistent tension control can cause uneven stretching or width variation at different points, leading to fabric distortion or inconsistent finished dimensions — careful tension control throughout is essential for consistent quality.', 2, '{"tension-control-continuous"}'::text[]);
COMMIT;
