SELECT set_config('request.jwt.claim.role','service_role',false);
SELECT set_config('request.jwt.claim.sub','f49d6153-1835-4455-81f3-2918d5d3484e',false);
BEGIN;
INSERT INTO public.qb_questions (subject_id, difficulty, question_type, question_text, options, correct_answer, explanation, points, tags) VALUES
('33333333-3333-3333-3333-333333333333', 'basic', 'multiple_choice', 'What is a ''beck'' (winch) dyeing machine, and what fabric form does it typically process?', '["An older-style rope-dyeing machine that circulates fabric using a rotating winch reel through a dye bath","A machine used only for open-width printing, never dyeing","A machine used exclusively for yarn package dyeing, never fabric","A modern computer-controlled continuous dyeing range"]'::jsonb, 'An older-style rope-dyeing machine that circulates fabric using a rotating winch reel through a dye bath', 'A beck (winch) dyeing machine circulates fabric in rope form through a dye bath using a rotating reel (winch) at the top of the machine — a traditional, relatively simple rope-dyeing method still used for various fabric types.', 1, '{"beck-dyeing"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'basic', 'multiple_choice', 'What is the purpose of a ''sample dyeing'' machine (small-batch dyeing equipment) in a mill''s technical department?', '["To dye small test samples for shade approval/recipe development before committing to full bulk dyeing","To dye the entire bulk production order in miniature batches","A machine used only for washing finished garments, unrelated to dyeing","A machine used exclusively for printing patterns onto fabric"]'::jsonb, 'To dye small test samples for shade approval/recipe development before committing to full bulk dyeing', 'Sample dyeing equipment processes small fabric/yarn samples under controlled lab conditions, allowing technicians to develop and verify dye recipes (lab dips) before committing to costly, time-consuming full bulk dyeing.', 1, '{"sample-dyeing"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'What is ''desize, scour, bleach in one bath'' (combined pretreatment) generally intended to achieve for a mill''s operations?', '["Reducing total processing time, water, and energy use by combining multiple pretreatment steps into a single bath/cycle where chemistry allows","This approach always produces worse fabric quality than fully separate processing steps","Combined pretreatment eliminates the need for any dyeing step afterward","This term describes a fabric defect, not a processing efficiency approach"]'::jsonb, 'Reducing total processing time, water, and energy use by combining multiple pretreatment steps into a single bath/cycle where chemistry allows', 'Where compatible chemistry allows, combining desizing, scouring, and bleaching into fewer baths/cycles reduces total water, energy, and time consumption versus running each as a fully separate process with its own heating and rinsing — an efficiency approach many modern mills adopt when quality requirements permit.', 2, '{"combined-pretreatment"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'basic', 'multiple_choice', 'What is the purpose of ''color kitchen'' (or dye kitchen) automation in a modern dye house?', '["Automatically weighing and dispensing precise dye/chemical quantities according to a recipe, reducing manual weighing errors","A kitchen area where factory workers prepare their meals","A system used only for tracking factory worker attendance","A machine used exclusively for cutting fabric, unrelated to dyeing"]'::jsonb, 'Automatically weighing and dispensing precise dye/chemical quantities according to a recipe, reducing manual weighing errors', 'An automated color/dye kitchen precisely weighs and dispenses dyes and chemicals according to a digital recipe, reducing human weighing errors, improving batch-to-batch consistency, and speeding up recipe preparation compared to fully manual weighing.', 1, '{"color-kitchen-automation"}'::text[]),
('33333333-3333-3333-3333-333333333333', 'intermediate', 'multiple_choice', 'Why does automated dye/chemical dispensing (color kitchen) generally improve shade consistency across production batches compared to manual weighing?', '["It eliminates human error in weighing small quantities precisely, ensuring each batch receives the exact same dye/chemical amounts as specified in the recipe","Automated dispensing has no effect on weighing accuracy compared to manual methods","Manual weighing is always more precise than any automated system","Shade consistency depends only on the dyeing machine, not on how accurately chemicals are dosed"]'::jsonb, 'It eliminates human error in weighing small quantities precisely, ensuring each batch receives the exact same dye/chemical amounts as specified in the recipe', 'Manual weighing of small dye quantities is prone to human error/inconsistency (especially at very low percentages); automated dispensing systems precisely and repeatably measure exact quantities every time, directly improving batch-to-batch shade consistency.', 2, '{"automated-dispensing-consistency"}'::text[]);
COMMIT;
