-- ============================================================
-- 000-bootstrap-core-schema.sql (AUTO-GENERATED, best-effort)
--
-- These 52 tables predate migration tracking entirely (never appear as
-- CREATE TABLE in supabase/migrations/) -- they were part of Lovable's
-- initial project scaffold before formal migrations started. Reconstructed
-- here from src/integrations/supabase/types.ts (the auto-generated TS
-- types, which reflects the full final schema including these tables).
--
-- IMPRECISE BY NECESSITY: types.ts gives column names/nullability/FK
-- relationships but NOT exact Postgres types (string could be text/uuid/
-- timestamptz), NOT default values, NOT CHECK constraints, NOT indexes.
-- Types/defaults below are inferred by naming convention. No RLS policies
-- are defined here (later migrations ALTER these tables and add policies
-- once the tables exist -- if a table gets no later policy, add one
-- during Phase 3 testing when a real query 403s unexpectedly).
--
-- Enums (from Constants.public.Enums in types.ts, taken verbatim -- exact).
-- ============================================================

DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('super_admin','admin','chief_marketer','content_writer','instructor','student');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.class_video_platform AS ENUM ('upload','drive','youtube');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.class_video_visibility AS ENUM ('public','logged_in','paid');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.qb_difficulty AS ENUM ('basic','intermediate','advanced');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.qb_leaderboard_period AS ENUM ('all_time','monthly','weekly');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.qb_question_source AS ENUM ('manual','bulk','ai');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.qb_question_type AS ENUM ('multiple_choice','true_false','short_answer');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.workshop_registration_status AS ENUM ('registered','attended','cancelled','no_show');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.workshop_status AS ENUM ('draft','published','ongoing','completed','cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.workshop_type AS ENUM ('one_day','multi_day');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public."admin_activity_log" (
  "action" text NOT NULL,
  "admin_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "details" jsonb DEFAULT '{}'::jsonb,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "target_id" uuid,
  "target_type" text
);
ALTER TABLE public."admin_activity_log" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."assignment_submissions" (
  "assignment_id" uuid NOT NULL,
  "feedback" text,
  "file_url" text,
  "graded_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "score" numeric,
  "status" text,
  "submission_text" text,
  "submitted_at" timestamptz DEFAULT now(),
  "user_id" uuid NOT NULL
);
ALTER TABLE public."assignment_submissions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."assignments" (
  "course_id" uuid,
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "due_days" numeric,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "instructions" text,
  "is_published" boolean DEFAULT false,
  "max_score" integer,
  "section_id" uuid,
  "sort_order" integer,
  "title" text NOT NULL
);
ALTER TABLE public."assignments" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."categories" (
  "icon_url" text,
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "name" text NOT NULL,
  "parent_id" integer,
  "slug" text NOT NULL,
  "sort_order" integer
);
ALTER TABLE public."categories" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."certificate_templates" (
  "background_url" text,
  "created_at" timestamptz DEFAULT now(),
  "created_by" uuid,
  "custom_texts" jsonb DEFAULT '{}'::jsonb,
  "download_rule" text NOT NULL,
  "fields_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "min_score_pct" integer,
  "name" text NOT NULL,
  "updated_at" timestamptz DEFAULT now()
);
ALTER TABLE public."certificate_templates" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."certificates" (
  "certificate_number" text NOT NULL,
  "course_id" uuid,
  "download_count" integer,
  "downloaded_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "issued_at" timestamptz DEFAULT now(),
  "score_percentage" numeric,
  "template_snapshot" jsonb DEFAULT '{}'::jsonb,
  "user_id" uuid NOT NULL,
  "workshop_id" uuid
);
ALTER TABLE public."certificates" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."class_video_comment_likes" (
  "comment_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."class_video_comment_likes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."class_video_comments" (
  "content" text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "likes_count" integer DEFAULT 0 NOT NULL,
  "parent_id" uuid,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "user_id" uuid NOT NULL,
  "video_id" uuid NOT NULL
);
ALTER TABLE public."class_video_comments" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."class_video_likes" (
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "video_id" uuid NOT NULL
);
ALTER TABLE public."class_video_likes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."class_video_views" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "session_key" text,
  "user_id" uuid,
  "video_id" uuid NOT NULL,
  "viewed_at" timestamptz DEFAULT now() NOT NULL
);
ALTER TABLE public."class_video_views" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."class_videos" (
  "category_id" uuid,
  "clip_end_seconds" numeric,
  "clip_start_seconds" numeric DEFAULT 0 NOT NULL,
  "comments_count" integer DEFAULT 0 NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "description" text,
  "duration_seconds" numeric,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_featured" boolean DEFAULT false NOT NULL,
  "is_published" boolean DEFAULT false NOT NULL,
  "likes_count" integer DEFAULT 0 NOT NULL,
  "required_course_id" uuid,
  "slug" text NOT NULL,
  "tags" text[] NOT NULL,
  "thumbnail_url" text,
  "title" text NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "uploaded_by" uuid,
  "video_platform" class_video_platform NOT NULL,
  "video_url" text NOT NULL,
  "views_count" integer DEFAULT 0 NOT NULL,
  "visibility" class_video_visibility NOT NULL
);
ALTER TABLE public."class_videos" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."cloudinary_accounts" (
  "api_key" text NOT NULL,
  "api_secret" text NOT NULL,
  "cloud_name" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "file_category" text NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_primary" boolean DEFAULT false,
  "nickname" text NOT NULL,
  "status" text,
  "updated_at" timestamptz DEFAULT now(),
  "upload_preset" text NOT NULL,
  "usage_pct" numeric
);
ALTER TABLE public."cloudinary_accounts" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."coupon_usages" (
  "coupon_id" uuid,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "order_id" uuid,
  "used_at" timestamptz DEFAULT now(),
  "user_id" uuid
);
ALTER TABLE public."coupon_usages" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."coupons" (
  "applicable_ids" text[],
  "applicable_to" text,
  "applicable_type" text NOT NULL,
  "code" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "discount_type" text NOT NULL,
  "discount_value" integer DEFAULT 0 NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_active" boolean DEFAULT false,
  "max_discount_amount" integer,
  "min_order_amount" integer,
  "per_user_limit" numeric,
  "usage_limit" numeric,
  "used_count" integer,
  "valid_from" text,
  "valid_until" text
);
ALTER TABLE public."coupons" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."course_sections" (
  "course_id" uuid NOT NULL,
  "description" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "materials" jsonb DEFAULT '{}'::jsonb,
  "sort_order" integer,
  "title" text NOT NULL
);
ALTER TABLE public."course_sections" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."courses" (
  "avg_rating" numeric,
  "category_id" integer,
  "cert_template_id" uuid,
  "certificate_template_id" numeric,
  "certificate_threshold_pct" numeric,
  "content_drip_enabled" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "difficulty_level" text,
  "discount_ends_at" timestamptz DEFAULT now(),
  "discount_price" integer,
  "enrollment_count" integer,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "instructor_id" uuid,
  "intro_video_url" text,
  "is_public" boolean DEFAULT false,
  "is_published" boolean DEFAULT false,
  "language" text,
  "max_students" integer,
  "meta_description" text,
  "meta_title" text,
  "og_image_url" text,
  "prerequisite_course_ids" text[],
  "price" numeric,
  "rejection_reason" text,
  "revenue_share_pct" numeric,
  "review_count" integer,
  "review_status" text,
  "short_description" text,
  "slug" text NOT NULL,
  "thumbnail_url" text,
  "title" text NOT NULL,
  "total_duration_minutes" integer,
  "total_lessons" integer,
  "updated_at" timestamptz DEFAULT now()
);
ALTER TABLE public."courses" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."discussions" (
  "content" text NOT NULL,
  "course_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_answered" boolean DEFAULT false,
  "is_closed" boolean DEFAULT false NOT NULL,
  "is_pinned" boolean DEFAULT false NOT NULL,
  "lesson_id" uuid,
  "parent_id" uuid,
  "upvote_count" integer DEFAULT 0 NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."discussions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."ebook_access_tokens" (
  "created_at" timestamptz DEFAULT now(),
  "ebook_id" uuid NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "token" text NOT NULL,
  "used" boolean DEFAULT false,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."ebook_access_tokens" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."ebook_reading_progress" (
  "brightness" numeric,
  "current_page" numeric,
  "ebook_id" uuid NOT NULL,
  "font_size" numeric,
  "highlights" jsonb DEFAULT '{}'::jsonb,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "notes" jsonb DEFAULT '{}'::jsonb,
  "progress_pct" numeric,
  "reading_mode" text,
  "total_pages" integer,
  "updated_at" timestamptz DEFAULT now(),
  "user_id" uuid NOT NULL
);
ALTER TABLE public."ebook_reading_progress" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."ebooks" (
  "age_restriction" text,
  "author" text,
  "category_id" integer,
  "cover_url" text,
  "created_at" timestamptz DEFAULT now(),
  "created_by" uuid,
  "description" text,
  "discount_price" integer,
  "download_count" integer,
  "file_format" text,
  "file_url" text,
  "gallery_urls" text[],
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_published" boolean DEFAULT false,
  "meta_description" text,
  "meta_keywords" text,
  "meta_title" text,
  "og_image_url" text,
  "page_count" integer,
  "price" numeric,
  "seo_keywords" text,
  "slug" text NOT NULL,
  "sub_writers" text[],
  "tags" text[],
  "title" text NOT NULL,
  "total_revenue" integer
);
ALTER TABLE public."ebooks" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."enrollments" (
  "completed_at" timestamptz DEFAULT now(),
  "course_id" uuid NOT NULL,
  "enrolled_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "payment_id" uuid,
  "progress_pct" numeric,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."enrollments" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."gradebook_manual_marks" (
  "course_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "label" text NOT NULL,
  "max_score" integer DEFAULT 0 NOT NULL,
  "notes" text,
  "score" numeric DEFAULT 0 NOT NULL,
  "updated_by" uuid,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."gradebook_manual_marks" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."hero_slides" (
  "countdown_target" text,
  "created_at" timestamptz DEFAULT now(),
  "cta_link" text,
  "cta_text" text,
  "gradient_direction" text,
  "gradient_from" text,
  "gradient_to" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "image_url" text,
  "is_active" boolean DEFAULT false,
  "overlay_opacity" numeric,
  "secondary_cta_link" text,
  "secondary_cta_text" text,
  "sort_order" integer,
  "subtitle" text,
  "subtitle_color" text,
  "text_alignment" text,
  "title" text NOT NULL,
  "title_color" text
);
ALTER TABLE public."hero_slides" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."instructor_applications" (
  "admin_notes" text,
  "bio" text,
  "created_at" timestamptz DEFAULT now(),
  "email" text NOT NULL,
  "experience_years" numeric,
  "expertise" text NOT NULL,
  "full_name" text NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "linkedin_url" text,
  "motivation" text,
  "phone" text,
  "qualification" text,
  "reviewed_at" timestamptz DEFAULT now(),
  "reviewed_by" uuid,
  "sample_video_url" text,
  "status" text NOT NULL,
  "university" text,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."instructor_applications" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."invoices" (
  "billing_district" text,
  "billing_email" text,
  "billing_name" text,
  "billing_phone" text,
  "coupon_code" text,
  "created_at" timestamptz DEFAULT now(),
  "discount_amount" integer,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "invoice_number" text NOT NULL,
  "order_id" uuid,
  "paid_at" timestamptz DEFAULT now(),
  "payment_method" text,
  "payment_status" text,
  "subtotal" numeric DEFAULT 0 NOT NULL,
  "total" numeric DEFAULT 0 NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."invoices" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."lesson_materials" (
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "lesson_id" uuid NOT NULL,
  "material_id" uuid NOT NULL,
  "material_type" text NOT NULL,
  "sort_order" integer
);
ALTER TABLE public."lesson_materials" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."lesson_progress" (
  "completed" boolean DEFAULT false,
  "completed_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "last_position_seconds" integer,
  "lesson_id" uuid NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."lesson_progress" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."lessons" (
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "duration_minutes" integer,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "instructor_notes" text,
  "is_preview" boolean DEFAULT false,
  "lesson_type" text,
  "live_class_platform" text,
  "live_class_url" text,
  "resource_url" text,
  "resources" jsonb DEFAULT '{}'::jsonb,
  "scheduled_unlock_at" timestamptz DEFAULT now(),
  "section_id" uuid,
  "sort_order" integer,
  "status" text,
  "title" text NOT NULL,
  "video_platform" text,
  "video_url" text
);
ALTER TABLE public."lessons" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."media_library" (
  "alt_text" text,
  "created_at" timestamptz DEFAULT now(),
  "file_name" text NOT NULL,
  "file_size" numeric,
  "file_type" text,
  "file_url" text NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "uploaded_by" uuid
);
ALTER TABLE public."media_library" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."media_references" (
  "cloudinary_account_id" uuid,
  "created_at" timestamptz DEFAULT now(),
  "fallback_url" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "owner_id" uuid,
  "owner_type" text NOT NULL,
  "public_id" text,
  "storage_source" text NOT NULL,
  "url" text NOT NULL
);
ALTER TABLE public."media_references" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."menus" (
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "items" jsonb DEFAULT '{}'::jsonb,
  "location" text NOT NULL,
  "name" text NOT NULL,
  "updated_at" timestamptz DEFAULT now()
);
ALTER TABLE public."menus" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."notifications" (
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_read" boolean DEFAULT false,
  "link" text,
  "message" text NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb,
  "title" text NOT NULL,
  "type" text NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."notifications" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."order_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "item_id" uuid NOT NULL,
  "item_type" text NOT NULL,
  "order_id" uuid NOT NULL,
  "price" numeric DEFAULT 0 NOT NULL
);
ALTER TABLE public."order_items" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."orders" (
  "coupon_code" text,
  "created_at" timestamptz DEFAULT now(),
  "discount_amount" integer,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "payment_method" text,
  "payment_reference" text,
  "status" text,
  "total" numeric DEFAULT 0 NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."orders" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."pages" (
  "author_id" uuid,
  "content" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamptz DEFAULT now(),
  "featured_image_url" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "meta_description" text,
  "meta_title" text,
  "slug" text NOT NULL,
  "sort_order" integer,
  "status" text NOT NULL,
  "template" text,
  "title" text NOT NULL,
  "updated_at" timestamptz DEFAULT now()
);
ALTER TABLE public."pages" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."payment_gateways" (
  "created_at" timestamptz DEFAULT now(),
  "credentials" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "display_name" text NOT NULL,
  "gateway_name" text NOT NULL,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_active" boolean DEFAULT false NOT NULL,
  "updated_at" timestamptz DEFAULT now()
);
ALTER TABLE public."payment_gateways" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."posts" (
  "author_id" uuid,
  "category" text,
  "content" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamptz DEFAULT now(),
  "excerpt" text,
  "featured_image_url" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "meta_description" text,
  "meta_title" text,
  "og_image_url" text,
  "published_at" timestamptz DEFAULT now(),
  "seo_keywords" text,
  "slug" text NOT NULL,
  "status" text NOT NULL,
  "tags" text[],
  "title" text NOT NULL,
  "updated_at" timestamptz DEFAULT now()
);
ALTER TABLE public."posts" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."quiz_attempts" (
  "admin_feedback" text,
  "answers" jsonb DEFAULT '{}'::jsonb,
  "completed_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "ip_address" text,
  "manual_overrides" jsonb DEFAULT '{}'::jsonb,
  "passed" boolean DEFAULT false,
  "percentage" numeric,
  "quiz_id" uuid NOT NULL,
  "score" numeric,
  "started_at" timestamptz DEFAULT now(),
  "time_spent_seconds" numeric,
  "total_points" integer,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."quiz_attempts" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."quiz_questions" (
  "correct_answer" text NOT NULL,
  "explanation" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "image_url" text,
  "is_instruction" boolean DEFAULT false,
  "negative_marks" numeric,
  "options" jsonb DEFAULT '{}'::jsonb,
  "points" numeric,
  "question_text" text NOT NULL,
  "question_type" text,
  "quiz_id" uuid NOT NULL,
  "sequence_items" jsonb DEFAULT '{}'::jsonb,
  "sort_order" integer,
  "timer_seconds" numeric
);
ALTER TABLE public."quiz_questions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."quizzes" (
  "anti_cheat_enabled" boolean DEFAULT false,
  "auto_submit_on_blur" boolean DEFAULT false,
  "course_id" uuid,
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_published" boolean DEFAULT false,
  "lesson_id" uuid,
  "lock_ip" boolean DEFAULT false,
  "max_attempts" integer,
  "pass_percentage" numeric,
  "quiz_number" text,
  "randomize_options" boolean DEFAULT false,
  "randomize_questions" boolean DEFAULT false,
  "section_id" uuid,
  "sort_order" integer,
  "status" text,
  "time_limit_minutes" numeric,
  "timer_mode" text,
  "title" text NOT NULL
);
ALTER TABLE public."quizzes" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."referral_rewards" (
  "created_at" timestamptz DEFAULT now(),
  "credited_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "referred_id" uuid NOT NULL,
  "referrer_id" uuid NOT NULL,
  "reward_amount" numeric,
  "status" text
);
ALTER TABLE public."referral_rewards" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."refund_requests" (
  "amount" numeric NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "order_id" uuid,
  "processed_at" timestamptz DEFAULT now(),
  "processed_by" uuid,
  "reason" text,
  "refund_method" text NOT NULL,
  "status" text NOT NULL,
  "transaction_reference" text,
  "user_id" uuid
);
ALTER TABLE public."refund_requests" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."reviews" (
  "admin_response" text,
  "comment" text,
  "course_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_approved" boolean DEFAULT false,
  "rating" numeric NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."reviews" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."site_settings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "key" text NOT NULL,
  "updated_at" timestamptz DEFAULT now(),
  "value" text
);
ALTER TABLE public."site_settings" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."user_profiles" (
  "avatar_url" text,
  "batch" text,
  "bio" text,
  "blood_group" text,
  "business_type" text,
  "campus" text,
  "company_name" text,
  "country" text,
  "created_at" timestamptz DEFAULT now(),
  "current_job" text,
  "date_of_birth" date,
  "department" text,
  "district" text,
  "division" text,
  "expertise" text[],
  "facebook_url" text,
  "full_name" text,
  "gender" text,
  "github_url" text,
  "graduation_year" numeric,
  "headline" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_active" boolean DEFAULT false,
  "is_public_contributor" boolean DEFAULT false NOT NULL,
  "language_preference" text,
  "last_login_at" timestamptz DEFAULT now(),
  "latitude" numeric,
  "linkedin_url" text,
  "location_updated_at" timestamptz DEFAULT now(),
  "longitude" numeric,
  "name_last_changed_at" timestamptz DEFAULT now(),
  "occupation" text,
  "phone" text,
  "preferred_language" text,
  "professional_role" text,
  "referral_code" text,
  "referred_by" uuid,
  "roll_id" text,
  "social_links" jsonb DEFAULT '{}'::jsonb,
  "theme_preference" text,
  "university" text,
  "upazila" text,
  "updated_at" timestamptz DEFAULT now(),
  "username" text,
  "vote_count" integer DEFAULT 0 NOT NULL,
  "website_url" text,
  "whatsapp_number" text
);
ALTER TABLE public."user_profiles" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."user_roles" (
  "assigned_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "role" app_role NOT NULL,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."user_roles" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."video_categories" (
  "cover_url" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "description" text,
  "icon" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "is_active" boolean DEFAULT false NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL
);
ALTER TABLE public."video_categories" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."wallet_topup_requests" (
  "account_number" text,
  "admin_note" text,
  "amount" numeric NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "payment_method" text NOT NULL,
  "processed_at" timestamptz DEFAULT now(),
  "processed_by" uuid,
  "status" text NOT NULL,
  "transaction_id" text,
  "user_id" uuid NOT NULL
);
ALTER TABLE public."wallet_topup_requests" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."wallet_transactions" (
  "amount" numeric NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "reference_id" uuid,
  "type" text NOT NULL,
  "wallet_id" uuid NOT NULL
);
ALTER TABLE public."wallet_transactions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."wallets" (
  "balance" numeric,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  "updated_at" timestamptz DEFAULT now(),
  "user_id" uuid NOT NULL
);
ALTER TABLE public."wallets" ENABLE ROW LEVEL SECURITY;


-- public.has_role(): standard Supabase RLS-helper pattern, reconstructed
-- from its usage across every migration (public.has_role(auth.uid(), 'admin'::app_role)).
-- Defined AFTER the tables below since it queries public.user_roles.
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

-- public.handle_updated_at(): standard Supabase "bump updated_at on row
-- change" trigger helper, used by many "trg_*_updated_at" triggers.
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Constraints inferred from ON CONFLICT usage in later migrations (types.ts has no constraint info).
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.certificates ADD CONSTRAINT certificates_user_id_workshop_id_key UNIQUE (user_id, workshop_id);
